## **Text Representation**

1. BoW
2. TF-IDF
3. Word Embeddings

- `Corpus (C)` - all the text data or records of a dataset or a book
- `Vocabulary (V)` - consists of unique words present in a corpus
- `Document (D)` - One single text record of the dataset is a document. e.g. page, paragraph
- `Word (W)` - words present in a document. documents are made of words.

Text ---> and represent it in the language of computers?
- for them to comprehend text

### Character Encoding
- text into binary
- We have international standards for this
- 
- ASCII - 
    - 7 bit for character encoding
    - (A-Z, a-z, 0-9), and some basic punctuations as well
    - did not support emojis, special characters, non english, 
- UTF-8 - 
    - uses variable width 
    - uses 1 byte for standard english ---> makes it compatible with ASCII
    - 
- UTF - 16 ---> uses 2 to 4 bytes, UTF-32 ---> fixed 4 bytes

In [5]:
ord('A') ### ASCII code

letters = ['A', 'B', 'C', 'a', 'b', 'c', '!', '1','2','3']
[ord(w) for w in letters] # ASCII codes

[65, 66, 67, 97, 98, 99, 33, 49, 50, 51]

In [ ]:
letter = 'A'
encoded_letter  = 'A'.encode('utf-8')
encoded_letter.decode()
encoded_letter

'A'

## Label Encoding
- One Hot Encoding
- 
- Vector representation of categories
- 
- a - [1,0,0]
- b - [0,1,0]
- c - [0,0,1]

## Word Embedding
- are a way to represent words in numerical form so that computers can understand and process them more efficiently
- ![](https://media.geeksforgeeks.org/wp-content/uploads/20250530170636975663/Embeddings-in-Natural-Language-Processing.webp)

- Dense Vectors - represent or capture the **semantic meaning**, **context**, or relationship of words
- 
- "the cat sat on a mat" --->
- "cat is sitting on wall" --->
-

- vector databases ---> 
    - LLMs
    - Embeddings to represent text
    - vertical/relational db or is it better to use a vector database

---

### BoW - 
- describes the occurence of words within a document completely ignoring the order
- one of the simplest text representations
- counts how many times a word appears in a documents

In [14]:
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

corpus = [
    "Forests are green and beautiful.",
    "Green trees make a forest beautiful"
]

vectorizer = CountVectorizer()
bow_matrix = vectorizer.fit_transform(corpus) # Sparse Row sparse matrix of dtype 'int64'

bow_matrix.toarray() # convert to array

pd.DataFrame(bow_matrix.toarray(), columns = vectorizer.get_feature_names_out())

   and  are  beautiful  forest  forests  green  make  trees
0    1    1          1       0        1      1     0      0
1    0    0          1       1        0      1     1      1

- calculates frequencies of each of the words
- more repetition of a word, means more important it is

### TF-IDF - 
- evaluates importance of word, relative to the collection of documents (corpus)
- relative to whole of the text, how imporatant is a word

- It rewards the words that appear a lot in a specific `document` across the `corpus` ---> Term Frequency
- ![](https://media.geeksforgeeks.org/wp-content/uploads/20250207113146020518/The-TF-Formula.webp)
- it heavily penalizes words that appear in every document ---> Inverse Document Frequency
- penalizes more frequency
- ![](https://media.geeksforgeeks.org/wp-content/uploads/20250207113218469447/IDF-Formula.webp)
- 
- example:
    - 1000 articles
    - `the` appears everywhere in all the corpus ---> tfidf score = 0
    - word `jedi` appears 40 times in a specific article
    - tfidf will give this term a massive score ---> means this term is important for that document
    - `jedi` ---> article is related to starwars


![](https://media.geeksforgeeks.org/wp-content/uploads/20250813164205496346/idf_formula.webp)
-

In [ ]:
corpus = [
    "Forests are green and beautiful.",
    "Green trees make a forest beautiful"
]

from sklearn.feature_extraction.text import TfidfVectorizer

tf_idf = TfidfVectorizer()

tfidf_matrix = tf_idf.fit_transform(corpus)

tfidf_matrix.toarray() # tf-idf scores

pd.DataFrame(tfidf_matrix.toarray(), columns= tf_idf.get_feature_names_out())

idfs = tf_idf.idf_
words = tf_idf.get_feature_names_out()

pd.DataFrame(idfs.T, words)

                  0
and        1.405465
are        1.405465
beautiful  1.000000
forest     1.405465
forests    1.405465
green      1.000000
make       1.405465
trees      1.405465

In [38]:
tf_idf.vocabulary_

{'forests': 4,
 'are': 1,
 'green': 5,
 'and': 0,
 'beautiful': 2,
 'trees': 7,
 'make': 6,
 'forest': 3}

In [40]:
tfidf_matrix.toarray()
pd.DataFrame(tfidf_matrix.toarray(), columns= tf_idf.get_feature_names_out())

        and       are  beautiful  ...   green      make     trees
0  0.499221  0.499221     0.3552  ...  0.3552  0.000000  0.000000
1  0.000000  0.000000     0.3552  ...  0.3552  0.499221  0.499221

[2 rows x 8 columns]

- Scikit learn applies L2 Normalization to scale the vectors and Smooth IDF
- 
- the numbers might not match up ---> will appear smoothened
- 
#### Cosine Similarity -- 
- turn your documents into coordinates (because we vectorized them)
- CS will measure the angle between the cordinated
- same direction = 1, same document
- unrelated documents = 90 degrees, cos 90 = 0 ---> cosine similary is 0

In [42]:
corpus = [
    "Forests are green and beautiful.",
    "Green trees make a forest beautiful"
]

from sklearn.metrics.pairwise import cosine_similarity

similarity_mat = cosine_similarity(tfidf_matrix)

pd.DataFrame(similarity_mat, index = ['doc 1', 'doc 2'], columns = ['doc 1', 'doc 2'])

# multiple documents comared to multiple documents

          doc 1     doc 2
doc 1  1.000000  0.252334
doc 2  0.252334  1.000000

In [48]:
import spacy
nlp = spacy.load("en_core_web_sm")

word_1 = nlp("king")
word_2 = nlp("queen")
word_3 = nlp("man")
word_4 = nlp("woman")

print("king queen: ", word_1.similarity(word_2))
print("man woman: ", word_3.similarity(word_4))
print("man queen: ", word_3.similarity(word_2))
print("man king: ", word_3.similarity(word_1))
print("woman queen: ", word_2.similarity(word_4))

king queen:  0.4220200181007385
man woman:  0.8134351372718811
man queen:  0.41803663969039917
man king:  0.7392017841339111
woman queen:  0.34006255865097046

C:\Users\devid\AppData\Local\Temp\ipykernel_25336\1242647005.py:9: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print("king queen: ", word_1.similarity(word_2))
C:\Users\devid\AppData\Local\Temp\ipykernel_25336\1242647005.py:10: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print("man woman: ", word_3.similarity(word_4))
C:\Users\devid\AppData\Local\Temp\ipykernel_25336\1242647005.py:11: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print("man queen: ", word_3.similarity(word_2))
C:\Users\devid\AppData\Local\Temp\ipykernel_25336\1242647005.py:12: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print("man king: ", word_3.similarity(word_1))
C:\Users\devid\AppData\Local\Temp\ipykernel_25336\1242647005.py:13: UserWarning: [W007] The model you're using has no word vectors loaded, so the result of the Doc.similarity method will be based on the tagger, parser and NER, which may not give useful similarity judgements. This may happen if you're using one of the small models, e.g. `en_core_web_sm`, which don't ship with word vectors and only use context-sensitive tensors. You can always add your own word vectors, or use one of the larger models instead if available.
  print("woman queen: ", word_2.similarity(word_4))

![](https://media.geeksforgeeks.org/wp-content/uploads/20250530170636672412/Techniques-in-Embeddings-in-NLP.webp)

- Instead of counting words, we could plot them as Vectors using coordinates on a giant multidimension graph (300 dimensions)


![](https://miro.medium.com/max/1400/1*sAJdxEsDjsPMioHyzlN3_A.png)